### ISSUE TITLE
In Query window(s), a scratch pad like in PgAdmin III (RM #2800)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#1439]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/2800***
*Originally created by **Melvin Davidson** at 2017-10-16 13:17:24 UTC.*

Many times I copy or make notes from previous queries to use in subsequent
queries that I perform.
EG: table names and or key values.

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by RosscoPecoTrain** [comment]
I'd like to request this request be re-opened. Many sql ides allow support for executing the query at cursor. This saves considerable time from having to select then execute the query.
