### ISSUE TITLE
Grant wizard does not show privileges option again if Click on Back button on Privileges page (RM #1324)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#312]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1324***
*Originally created by **Fahar Abbas** at 2016-06-09 10:10:33 UTC.*

Tested Platform:
Windows 32/64

Installer location:
-------------------
https://www.pgadmin.org/download/windows4.php

Grant wizard does not show privileges option again if Click on Back button on Privileges page.

Step
-----
1. Install pgAdmin on Windows
2. Launch Install pg-9.6 server from enterprisedb.com
3. Server added successfully through pgAdmin4
4. create table test(a int);
5. table created on pgAdmin4
6. Expand database node
7. Select object type test and Click on Next
8. Privileges selection page open
9. Again Click on back button
10. Again Click on Next and see privileges page

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by pmwip0dx0** [comment]
> _**Issue migrated from Redmine: https://redmine.postgresql.org/issues/1324**_ _Originally created by **Fahar Abbas** at 2016-06-09 10:10:33 UTC._
> 
> Tested Platform: Windows 32/64
> 
> ## Installer location:
> https://www.pgadmin.org/download/windows4.php
> 
> Grant wizard does not show privileges option again if Click on Back button on Privileges page.
> 
> ## Step
> 1. Install pgAdmin on Windows
> 2. Launch Install pg-9.6 server from enterprisedb.com
> 3. Server added successfully through pgAdmin4
> 4. create table test(a int);
> 5. table created on pgAdmin4
> 6. Expand database node
> 7. Select object type test and Click on Next
> 8. Privileges selection page open
> 9. Again Click on back button
> 10. Again Click on Next and see privileges page
