### ISSUE TITLE
CSRF Token not found (RM #6085)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4018]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6085***
*Originally created by **Baran BÜYÜK** at 2020-12-10 12:25:07 UTC.*

I've been trying to fix an issue which is when I try to login to pgAdmin (in docker container )behind Nginx Proxy I'm getting an error that The CSRF tokens do not match.

Frankly, the problem is related within nginx or not I'm not sure but configuration files as below: 

@pgAdmin:
 image: dpage/pgadmin4
 networks:
   - my-network
 ports:
   - 9102:80
 environment:
   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
   - PGADMIN_CONFIG_SERVER_MODE=True
 volumes:
   - /home/docker-container/pgadmin/persist-data:/var/lib/pgadmin
   - /home/docker-container/pgadmin/persist-data/servers.json:/pgadmin4/servers.json
 deploy:
  placement:
    constraints: [node.hostname == my-host-name]@

*I've been trying to fix an issue which is when I try to login to pgAdmin (in docker container )behind Nginx Proxy I'm getting an error that The CSRF tokens do not match.

Frankly, the problem is related within nginx or not I'm not sure but configuration files as below:

Docker Swarm Service :

pgAdmin:
 image: dpage/pgadmin4
 networks:
   - my-network
 ports:
   - 9102:80
 environment:
   - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
   - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
   - PGADMIN_CONFIG_SERVER_MODE=True
 volumes:
   - /home/docker-container/pgadmin/persist-data:/var/lib/pgadmin
   - /home/docker-container/pgadmin/persist-data/servers.json:/pgadmin4/servers.json
 deploy:
  placement:
    constraints: [node.hostname == my-host-name]

Nginx Configuration:*

@server {

    listen 443 ssl;
    server_name my-server-name;

    location / {

            proxy_pass http://pgAdmin/;
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-CSRF-Token $http_x_pga_csrftoken;
    }

    ssl_certificate /home/nginx/ssl/certificate.crt;
    ssl_certificate_key /home/nginx/ssl/private.key;
    ssl_session_cache  builtin:1000  shared:SSL:10m;
    ssl_prefer_server_ciphers on;
    
server {

    listen 80;
    server_name my-server-name;
    return 301 https://my-server-name $request_uri;

 }@

I can able to access to pgAdmin in two ways :

The first way is direct host ip like 172.23.53.2:9102
The second way is via Nginx proxy.
When I try to access to pgAdmin via direct host ip there is no error but when I try to access to via dns ( like my-server.pgadmin.com ) I'm getting an error when I logged into pgAdmin dashboard.

The error is :

Bad Request

The CSRF tokens do not match.

My first opinion about this error is nginx does not pass CSRF Token header to pgAdmin. For these reason I've changed nginx configuration file many many times but I'm still getting this error.

What could be source of this error and how could I solve this problem?

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by chimisu** [comment]
@dpage hello,how did u solve it?I had the same issue.
