### ISSUE TITLE
v5 right clicking in SQL Editor kills pgAdmin (RM #6301)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4205]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6301***
*Originally created by **Arnaud Lesauvage** at 2021-03-09 09:50:14 UTC.*

On windows 10 64 bits, after upgrading to pgAdmin 4 v5.0, if I open an SQL Editor window, right clicking anywhere in the SQL Pane instantly closes all pgAdmin windows.
There is no error, and nothing particular shows in the log after setting FILE_LOG_LEVEL=DEBUG

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by thewildman** [comment]
This was not resolved when originally migrated to github (so issue was not resolved on sep 15), but for the record this bug was still present in 6.15 and was FIXED in 6.16.
