### ISSUE TITLE
Properties dialog should show master password dialog if crypt key missing (RM #6960)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4727]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/6960***
*Originally created by **Aditya Toshniwal** at 2021-10-26 05:26:54 UTC.*

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by jarrelldunson** [comment]
Can we open again... I get this error, when trying to connect to Postgres on AWS: "Crypt key is missing." Note: I don't get this error, when using DBeaver... just PG Admin4.

**Comment by jarrelldunson** [comment]
To all, you can disregard... this was fixed when I went from pgAdmin v6.14 to v6.15
 Jarrell
