### ISSUE TITLE
PassFile in server mode always prefixed with the storage dir (RM #7134)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#4864]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7134***
*Originally created by **Adrian Lopez** at 2022-01-21 09:03:39 UTC.*

In server mode, the PassFile is always prefixed with the storage dir ("code":https://github.com/postgres/pgadmin4/blob/1013d7ccdd3431d354fa0a23b987a13a919d8ad0/web/pgadmin/utils/__init__.py#L265).

If someone tries to configure an absolute passfile like: (as shown in "docs":https://www.pgadmin.org/docs/pgadmin4/development/import_export_servers.html)
<pre>
"PassFile": "/path/to/pgpassfile"
</pre>

The actual path checked will be something like:
<pre>
/var/lib/pgadmin/storage/admin_foo.bar/path/to/pgpassfile
</pre>

Maybe the `get_complete_file_path` should check if the path is absolute, and in that case, don't prefix the storage dir.

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by rijnhard** [comment]
If anything documentation should be updated to reflect this, wasted 3 hours before finding this.

there is another valid case: spinning up docker clusters,
I should be able to create a shared server by default from config (I am using docker secrets & config and Oauth for authentication).
doing this would actually mean we don't have to give out passwords to the db.
