### ISSUE TITLE
Allow Editing of Generated SQL from View/Edit Data Menu (RM #7465)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5139]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7465***
*Originally created by **Anthony DeBarros** at 2022-06-10 15:05:07 UTC.*

When a user selects any of the options under the View/Edit Data menu in the object browser, pgAdmin provides the generated SQL query and the result of the query (e.g., first 100 rows).

It would be helpful to then be able to edit the generated SQL to re-run the query in modified form and also to save a fresh query file.

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by mark-orion** [comment]
Why is this marked as closed and completed ? I am using the latest version 6.19 and I am still not able to edit the queries shown/generated on the View/Edit Data page. I might have missed something, but otherwise this is highly inconvenient.

**Comment by dpage** [comment]
Because the import script used to migrate from Redmine was only able to close an issue in that way. The issue was closed originally on Redline because it was a duplicate, as noted above.

**Comment by dpage** [comment]
No, because it's a duplicate ticket. The original one (https://github.com/pgadmin-org/pgadmin4/issues/3499) is also closed though, because there are other ways of getting an editable script, and general consensus amongst users was that that method is preferred and the View/Edit Data method should stay as-is.

**Comment by mark-orion** [comment]
understand. Thanks for the quick reponse.
