### ISSUE TITLE
uwsgi + nginx db backup does not work (RM #7580)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5230]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7580***
*Originally created by **Jonny Rimkus** at 2022-07-31 06:11:53 UTC.*

Hi, 
I'm running pgadmin 6.12 via uwsgi+nginx and configured it according to the Docs:
https://www.pgadmin.org/docs/pgadmin4/latest/server_deployment.html#nginx-configuration-with-uwsgi

my uwsgi version is 2.0.20 (installed via pip)

I've added the correct binary path, and the Validation shows:
pg_dump: (PostgreSQL) 13.7
pg_dumpall: (PostgreSQL) 13.7
pg_restore: (PostgreSQL) 13.7
psql: (PostgreSQL) 13.7

When I try to use these commands via e.g right click on a Schema->Backup, entering a Filename for the Backup nothing happens.
When I open the Filebrowser I see The file, but it is empty.

I enabled debug logging for pgadmin, and I see the following in the logs:

*pgadmin4.log* (FILE_LOG_LEVEL = 10 /*DEBUG*/)
<pre>
2022-07-31 07:55:21,366: INFO   pgadmin:        Executing the process executor with the arguments: ['/path/to/uwsgi', '/path/to/pgadmin/lib/python3.9/site-packages/p
gadmin4/pgadmin/misc/bgprocess/process_executor.py', '/usr/bin/pg_dump', '--file', '/path/to/pgadmin/storage/folder/backup_file', '--host', 'localhost', '--port', '46787', '--use
rname', 'username', '--no-password', '--verbose', '--format=c', '--blobs', '--schema', 'public', 'schema_name']
</pre>

*uwsgi log*
<pre>
*** Starting uWSGI 2.0.20 (64bit) on [Sun Jul 31 07:53:43 2022] ***
compiled with version: 9.3.1 20200408 (Red Hat 9.3.1-2) on 02 June 2022 09:12:33
os: Linux-3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022
nodename: server.domain.name
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 20
current working directory: /path/to/uwsgi/conf/dir/apps-enabled
detected binary path: /path/to/uwsgi/bin/uwsgi
chdir() to /path/to/pgadmin/lib/python3.9/site-packages/pgadmin4
your processes number limit is 103763
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /path/to/uwsgi/socket/pgadmin.uwsgi.sock fd 6
Python version: 3.9.13 (main, May 23 2022, 15:17:00)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
PEP 405 virtualenv detected: /path/to/pgadmin
Set PythonHome to /path/to/pgadmin
Python main interpreter initialized at 0x13bdbf0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 647728 bytes (632 KB) for 25 cores
*** Operational MODE: threaded ***
mounting pgAdmin4:app on /
WSGI app 0 (mountpoint='/') ready in 7 seconds on interpreter 0x13bdbf0 pid: 24486 (default app)
spawned uWSGI master process (pid: 24486)
spawned uWSGI worker 1 (pid: 24685, cores: 25)
announcing my loyalty to the Emperor...
*** has_emperor mode detected (fd: 9) ***
/path/to/bin/uwsgi: unrecognized option '--host'
</pre>

I think the relevant line is */path/to/bin/uwsgi: unrecognized option '--host'* from the uwsgi.log and seems identical to the error described here: https://www.reddit.com/r/PostgreSQL/comments/osb3t7/comment/hb5w2z0/?utm_source=share&utm_medium=web2x&context=3

What can I do to get the Backup functionality working with nginx+uwsgi

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by ravermeister** [comment]
Hi, 
unfortunately this issue is still not resolved. 
As I had mentioned earlier the python path isn't correctly determined here: https://github.com/pgadmin-org/pgadmin4/blob/5a5da5f7206805168d0822ed7ea1efe5c4c5212b/web/pgadmin/misc/bgprocess/processes.py#L269
The Scenario of this issue is as follows:
1. python is installed **system wide**
```shell
[raver7@finlay ~]$ which python
alias python='python3.9'
	/usr/bin/python3.9
```
2. The UWSGI installation was done via `pip install --user uwsgi` 
```shell
[raver7@finlay ~]$ ls -l /home/raver7/.local/bin/
insgesamt 1260
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip3
-rwxrwxr-x. 1 raver7 raver7     223 22. Aug 10:51 pip3.9
-rwxrwxr-x. 1 raver7 raver7 1276576 17. Jul 08:57 uwsgi

```
3. pgadmin3 was installed using a virtualenv in `/home/raver7/share/pgadmin`:
```shell
[raver7@finlay ~]$ source /home/raver7/share/pgadmin/bin/activate
(pgadmin) [raver7@finlay ~]$ echo $VIRTUAL_ENV
/home/raver7/share/pgadmin

``` 
4. So the *correct* Python path would be inside the virtualenv folder:
```
(pgadmin) [raver7@finlay ~]$ ls -l $VIRTUAL_ENV/bin
insgesamt 88
-rw-r--r--. 1 raver7 raver7 1904  2. Jun 12:02 activate
-rw-r--r--. 1 raver7 raver7  853  2. Jun 12:02 activate.csh
-rw-r--r--. 1 raver7 raver7 1993  2. Jun 12:02 activate.fish
-rw-r--r--. 1 raver7 raver7 8834  2. Jun 12:02 Activate.ps1
-rwxrwxr-x. 1 raver7 raver7  237 16. Sep 09:57 alembic
-rwxrwxr-x. 1 raver7 raver7  245 16. Sep 09:57 chardetect
-rwxrwxr-x. 1 raver7 raver7  238 16. Sep 09:57 email_validator
-rwxrwxr-x. 1 raver7 raver7  232 16. Sep 09:57 flask
-rwxrwxr-x. 1 raver7 raver7 1719 16. Sep 09:57 jp.py
-rwxrwxr-x. 1 raver7 raver7  237 16. Sep 09:57 mako-render
-rwxrwxr-x. 1 raver7 raver7  268 17. Jul 09:25 normalizer
-rwxrwxr-x. 1 raver7 raver7  240 16. Sep 09:58 pgadmin4
-rwxrwxr-x. 1 raver7 raver7  245 27. Aug 11:18 pip
-rwxrwxr-x. 1 raver7 raver7  245 27. Aug 11:18 pip3
-rwxrwxr-x. 1 raver7 raver7  245 27. Aug 11:18 pip3.9
-rwxrwxr-x. 1 raver7 raver7  246 16. Sep 09:57 pybabel
drwxrwxr-x. 2 raver7 raver7   31 16. Sep 09:57 __pycache__
lrwxrwxrwx. 1 raver7 raver7    9  2. Jun 12:02 python -> python3.9
lrwxrwxrwx. 1 raver7 raver7    9  2. Jun 12:02 python3 -> python3.9
lrwxrwxrwx. 1 raver7 raver7   18  2. Jun 12:02 python3.9 -> /usr/bin/python3.9
-rwxrwxr-x. 1 raver7 raver7  245 16. Sep 09:57 qr
-rwxrwxr-x. 1 raver7 raver7  240 16. Sep 09:57 sqlformat
-rwxrwxr-x. 1 raver7 raver7  242 16. Sep 09:57 sshtunnel
-rwxrwxr-x. 1 raver7 raver7  232  2. Jun 12:03 wheel
```

I've tested with the mentioned Version https://ftp.postgresql.org/pub/pgadmin/pgadmin4/snapshots/2022-09-12/pgadmin4-6.13-py3-none-any.whl and I get the Error which correctly says it couldn't find the python executable at the determined directory:
![image](https://user-images.githubusercontent.com/6666963/190588244-786215b2-ad19-4494-a337-3ad7c7c04ffd.png)

In my Opinion the best solution would be to check if pgadmin is running from within a **virtualenv** by checking if the System Environment Variable  `$VIRTUAL_ENV` exists, and then for the existance of `$VIRTUAL_ENV/bin/python`
