### ISSUE TITLE
WHEN logout, brower display {"success":0,"errormsg":"Crypt key is missing.","info":"CRYPTKEY_MISSING","result":null,"data":null} (RM #7614)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5256]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7614***
*Originally created by **jin tao** at 2022-08-15 10:00:09 UTC.*

1. pgadmin4 run on SERVER_MODE = True.
2. Open a QUery Tool and then click logout.
4. The browser returns a JSON instead of returning to the login web ({"success":0,"errormsg":"Crypt key is missing.","info":"CRYPTKEY_MISSING","result":null,"data":null}) .

**Comment by jarrelldunson** [comment]
Can we open again... I get this error, when trying to connect to Postgres on AWS: "Crypt key is missing."   Note: I don't get this error, when using DBeaver... just PG Admin4.

**Comment by jarrelldunson** [comment]
To all, you can disregard... this was fixed when I went from pgAdmin v6.14 to v6.15
 Jarrell
