### ISSUE TITLE
column "backend_type" does not exist (RM #7645)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#5283]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7645***
*Originally created by **Marian Wendt** at 2022-08-26 06:05:17 UTC.*

On the Postgresql server version 9.6, the dashboard produces this error (retrieving connection details).
The error does not occur in version pgAdmin4-6.11 (6.12 not tested).
** The error should be very easy to fix, as corresponding version distinctions have already been made in previous versions. **

**Comment by dpage** [comment]
Issue closed on Redmine.

**Comment by fhaut** [comment]
Hi there, Franklin here.  Let me add comment...


Enviroment:
* Win11
* PostgreSQL Server 9.6 version 9.6.24, with locale = "C"
* PGAdmin4 - from https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-10-08/

Getting image error below

![image](https://user-images.githubusercontent.com/2178618/194702782-5592e7c4-ce36-4b38-a8e7-d3a74c2cf4f1.png)

the version 9.6 is breaking change to many applications, and needs time to grave support, please reconsider add support to pgAdmin4 to this server version. 

Thanks!
